name: Test Build Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: danielvm-git/.github/.github/workflows/test-build-release-static.yml@v1
    with:
      site_url: "https://danielvm-git.github.io/astro-wiki"
      release_tool: "big-release"
    secrets: inherit
