name: Test Build Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: danielvm-git/.github/.github/workflows/test-build-release-static.yml@2e1bd382ecb9f1b96febbb708c8bace2b6408014
    with:
      site_url: "https://danielvm-git.github.io/astro-wiki"
      release_tool: "big-release"
